### ISSUE TITLE
FAST_ENTIRE_SCRIPT: b.units() is broken

### ISSUE THREAD

**Issue by basiljs** [basiljs/basil.js#19] opened 2013-10-29 14:05 UTC
Calls to b.units() are still changing the units for basil.js, but some depending functions are not working anymore. I don't have an isolated example at hand, but please check the following ornaments generator. The program should fill the entire page. It does, if ENTIRE_SCRIPT is chosen instead. If the program is run again, the MM units are working properly, apparently since the default units stay changed then and are evaluated the next time...
# includepath "~/Documents/;%USERPROFILE%Documents";
# include "basiljs/bundle/basil.js";

function draw() {

  var xCells = 30; // the amount of horizontal cells
  var yCells = 30; // the amount of vertical rows
  var center = false; // whether to center items in cells or not

  // check if shapes is existing
  if(b.items(b.layer("shapes")).length === 0) b.error("Nothing found on layer 'shapes'. Put something there first.");

  b.units(b.MM);

  var cellWidth = b.width / xCells; // calculate cell dimensions
  var cellHeight = b.height / yCells;

  for( var y = 0; y < yCells; y++) { // loop through rows

```
for( var x = 0; x < xCells; x++) { // loop through cells

  var shape = getRandomShape(); // get one of the shapes on the "shapes" layer, note that b. is not necessary for own functions

  b.layer("generated"); // set or create the layer "generated" as target

   b.rotate( b.random(b.TWO_PI / xCells) );  // set rotation for new item, 2 x Pi is a full rotation
```

//~       b.scale( 1.001 );        // set scaling for new item

```
  var newShape = b.duplicate(shape); // create a copy of the shape

  if(center == true) {
    // move new shape to position in the grid
    // cellHeight multiplied by y it gives the right y position. Same for the x axis.
    // add half of cell size to center in cell
    // substract half of object size to center at cell center
    b.itemX( newShape, cellWidth * x + cellWidth / 2 - b.bounds(newShape).width / 2 ); 
    b.itemY( newShape, cellHeight * y + cellHeight / 2 - b.bounds(newShape).height / 2 ); 
  } else {
    // without centering
    b.itemX( newShape, cellWidth * x ); 
    b.itemY( newShape, cellHeight * y ); 
  }

}
```

  }

}

// this is a custom made function
function getRandomShape() {

  var shapesLayer = b.layer("shapes"); // get the layer called "shapes"
  var shapesItems = b.items(shapesLayer); // get all the items on that layer as an array

  var randomIndex = b.floor(b.random( shapesItems.length )); // get a random number between 0 - shapesItems.length and round it down

  return shapesItems[ randomIndex ]; // get the shape at the calculated random position in the array and return it

}

b.go(); // the actual starting point of the sketch, go() is calling the draw() function

**Comment by fabiantheblind** [comment] 2016-07-06 13:13
Setting the units to MM is an enhancement. See #48

**Comment by trych** [comment] 2016-07-18 18:24
How exactly does the script not work as expected for you, @basiljs ( @ludzeller I guess? )?

Both provided examples work as expected for me (Mac OS X 10.8.5, ID CS 6), the first one fills the entire page, the second one places the square in the center no matter if I comment the `b.units( b.MM )` or not.

Is anybody else having issues with this? @fabiantheblind ?

**Comment by trych** [comment] 2016-07-18 18:59
Is it possible that the issues are caused by the fact that `RulerOrigin.PAGE_ORIGIN` is used instead of `RulerOrigin.SPREAD_ORIGIN` (see [includes/core Line 208](https://github.com/basiljs/basil.js/blob/master/includes/core.js#L208))?

Using `RulerOrigin.PAGE_ORIGIN` seems to be buggy in general with multi page spreads and therefore behaves quite unpredictable often.

See [this (german) thread](http://www.hilfdirselbst.ch/foren/Falsche_page_bounds-Werte_bei_Ansichtseinstellung_%84Lineal_am_Bund%93_P549173.html) about this issue, specifically Uwe Laubender's answers and examples. An english translation of the issue can be found [here](https://forums.adobe.com/thread/2145898), without any answers though.

I would suggest to change the basil.js to internally work with `https://forums.adobe.com/thread/2145898` only. Does anybody know, if this would be complicated to change?

**Comment by fabiantheblind** [comment] 2016-07-19 04:25
I did run into this error yet. Let me investigate. I'm still in finishing this semester and have a workshop coming up. So my timeframe for work on Basil starts in August.

**Comment by fabiantheblind** [comment] 2016-07-19 04:45
Just a guess. Changing to SPREAD_ORIGIN can mess up documents with facing pages. If set the 0/0 point will not be the upper left corner of the page.

**Comment by trych** [comment] 2016-07-19 12:00
Well, this error _does_ occur when you use the bounds of the page object together with SPINE_ORIGIN or PAGE_ORIGIN. However, I am not sure, if that leads to any problems with basil.js; if not, then we are fine of course. Also, after testing some more, I don't think this causes problems in this case here.

Without knowing what exactly went wrong though there is not much we can do, I think. I cannot recreate any errors at all.

**Comment by trych** [comment] 2019-12-04 20:31
Closing this, this is a really old bug that cannot really be reproduced and the `units()` function has been rewritten in the meantime.

**Closed by trych** 2019-12-04 20:31 UTC
Labels: bug
